### ISSUE TITLE
API /api/v2/tokens/ return price is 0

### ISSUE THREAD

**Issue by fanofthis** [pancakeswap/pancake-info-api#55]
I send request to API /api/v2/tokens/ to receive price of TBAKE token.
Contract of token is: 0x26D6e280F9687c463420908740AE59f712419147
But i receive price of this token is 0.

![image](https://user-images.githubusercontent.com/52544996/119094114-cb808880-ba3a-11eb-8339-f2acf76dcbad.png)

**Comment by SandroMiccoli** [comment]
Same here. 

Is this the same issue with #72 ?

Maybe the amount of decimal houses of the token price is too low?

**Comment by ChefKai** [comment]
We use a selective list of trusted assets (WBNB, BUSD, USDT, USDC, UST, VAI, BTCB, WETH, BETH) that a token must have a pair with in order to start indexing his price in USD and BNB; this avoid getting corrupted data when a token is having low liquidity as well, and/or a will to harm the ecosystem. You can check the logic within the [pancakeswap/pancake-subgraph](https://github.com/pancakeswap/pancake-subgraph) repository.
