### ISSUE TITLE
v2 API not working for a Token - Prices /volume not updating

### ISSUE THREAD

**Issue by BabyShibaInu** [pancakeswap/pancake-info-api#79]
Hello

We've been trying to workaround our API not showing values since days

Any way for you to look into this?
https://api.pancakeswap.info/api/v2/tokens/0xaecf6d1aff214fef70042740054f0f6d0caa98ab

https://pancakeswap.info/token/0xaecf6d1aff214fef70042740054f0f6d0caa98ab
It's the BNB pair that's not being shown in the .info , we really need it to go forward with our project since we can't seem to have a working price for CMC and CG or Blockfolio

Thanks!

**Comment by wbm0701** [comment]
i have the same ,how to update this info?

**Comment by ChefKai** [comment]
We use a selective list of trusted assets (WBNB, BUSD, USDT, USDC, UST, VAI, BTCB, WETH) that a token must have a pair with in order to start indexing his price in USD and BNB; this avoid getting corrupted data when a token is having low liquidity as well, and/or a will to harm the ecosystem. You can check the logic within the [pancakeswap/pancake-subgraph](https://github.com/pancakeswap/pancake-subgraph) repository.

If your token meet the above criteria, it's either a delay in the subgraph indexing the data, or a lack of liquidity for the pair (must to at least 10 BNB eq.), or a lack of 'trusted' pairs; in such case, it's advised to directly query the token price though a Binance Smart Chain node; or use a 3rd-party API that might fill this needs (BitQuery, Covalent, ...).

In your case, @BabyShibaInu your issue is solved because you met the above criteria, this is now resolved.

**Comment by ChefKai** [comment]
> i have the same ,how to update this info?

Please, read the above answer, and if this is not resolved, open a new issue.
