### ISSUE TITLE
update api info

### ISSUE THREAD

**Issue by ghost** [pancakeswap/pancake-info-api#88]
dont show  INFO https://pancakeswap.info/token/0x7f483b96cfcf0cc89d98e8215a36190eeeafa1cc

https://api.pancakeswap.info/api/v2/tokens/0x7f483b96cfcf0cc89d98e8215a36190eeeafa1cc

**Comment by ChefKai** [comment]
We use a selective list of trusted assets (WBNB, BUSD, USDT, USDC, UST, VAI, BTCB, WETH) that a token must have a pair with in order to start indexing his price in USD and BNB; this avoid getting corrupted data when a token is having low liquidity as well, and/or a will to harm the ecosystem. You can check the logic within the [pancakeswap/pancake-subgraph](https://github.com/pancakeswap/pancake-subgraph) repository.

If your token meet the above criteria, it's either a delay in the subgraph indexing the data, or a lack of liquidity for the pair (must to at least 10 BNB eq.), or a lack of 'trusted' pairs; in such case, it's advised to directly query the token price though a Binance Smart Chain node; or use a 3rd-party API that might fill this needs (BitQuery, Covalent, ...).
